#!/usr/bin/env python3
"""Regenerate every data-bearing figure input and results table of the arXiv
package from the committed harness CSVs in paper/experiments/results/.

    python3 paper/arxiv_ref/tools/make_artifacts.py

Writes figures/data/*.dat (read by pgfplots) and tables/{e1,e2,e3,e3_full,e4}.tex.
No number in those files is typed by hand."""
import csv
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
RES = PKG.parent / "experiments" / "results"
DATA = PKG / "figures" / "data"
TAB = PKG / "tables"
DATA.mkdir(parents=True, exist_ok=True)


def rows(name):
    with open(RES / name, newline="") as f:
        return [r for r in csv.DictReader(f) if not r[next(iter(r))].startswith("#")]


def tt(s):
    return r"\texttt{" + s.replace("_", r"\_") + "}"


def thou(x):
    """1234567.8 -> 1{,}234{,}567.8 (LaTeX thousands separator)."""
    ip, _, fp = f"{x}".partition(".")
    out = ""
    while len(ip) > 3:
        out = "{,}" + ip[-3:] + out
        ip = ip[:-3]
    return ip + out + ("." + fp if fp else "")


HDR = "%% AUTO-GENERATED by tools/make_artifacts.py from paper/experiments/results/%s -- do not edit\n"

# ---------------------------------------------------------------- E1
e1 = rows("e1_static_quality.csv")
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        with open(DATA / f"e1_{b}_{d}.dat", "w") as f:
            f.write("window f1 precision recall\n")
            for r in e1:
                if r["backend"] == b and r["density"] == d:
                    f.write(f"{r['window']} {float(r['f1']):.6f} {float(r['precision']):.6f} {float(r['recall']):.6f}\n")
last = max(int(r["window"]) for r in e1)
movers = {"low": 5, "med": 25, "high": 100}
lines = []
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        rr = [r for r in e1 if r["backend"] == b and r["density"] == d]
        first_full = min(int(r["window"]) for r in rr if float(r["recall"]) == 1.0)
        fin = [r for r in rr if int(r["window"]) == last][0]
        lines.append((b, d, first_full, fin))
best_p = max(float(l[3]["precision"]) for l in lines if l[1] == "high")
with open(TAB / "e1.tex", "w") as f:
    f.write(HDR % "e1_static_quality.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Static-layer quality (E1) against the %s-cell ground-truth wall set. "
            "\\emph{Recall~1 from} is the first window index $t$ at which recall reaches 1.0 "
            "(it never drops afterwards); precision, F1 and the predicted static-set size are at "
            "the final window $t{=}%d$. Single seed (12345), so no dispersion is reported. "
            "Bold marks the better backend under high clutter.}\n" % (lines[0][3]["gt_static"], last))
    f.write("\\label{tab:e1}\n\\small\n\\begin{tabular}{llcccc}\n\\toprule\n")
    f.write("Backend & Clutter (movers/window) & Recall 1 from & Precision & F1 & $|\\hat{\\mathcal{S}}|$ \\\\\n\\midrule\n")
    for i, (b, d, ff, fin) in enumerate(lines):
        p, f1 = float(fin["precision"]), float(fin["f1"])
        ps, fs = f"{p:.4f}", f"{f1:.4f}"
        if d == "high" and p == best_p:
            ps, fs = f"\\textbf{{{ps}}}", f"\\textbf{{{fs}}}"
        f.write(f"{tt(b)} & {d} ({movers[d]}) & $t{{=}}{ff}$ & {ps} & {fs} & {fin['pred_static']} \\\\\n")
        if i == 2:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E2
amp = rows("e2_amplitude_vs_length.csv")
cells = []
for r in amp:
    if r["cell"] not in cells:
        cells.append(r["cell"])
for c in cells:
    with open(DATA / f"e2_{c}.dat", "w") as f:
        f.write("len amp\n")
        for r in amp:
            if r["cell"] == c:
                f.write(f"{r['obs_length']} {abs(float(r['amplitude'])):.6f}\n")
cls = rows("e2_classification.csv")
summ = {r["metric"]: r for r in rows("e2_summary.csv")}
note = {"door_p8_4on4off": "50\\% duty", "door_p8_2on6off": "25\\% duty",
        "door_p4_2on2off": "50\\% duty"}
with open(TAB / "e2.tex", "w") as f:
    f.write(HDR % "e2_classification.csv, e2_summary.csv")
    tp, fp = int(summ["periodic_TPR"]["note"]), int(summ["periodic_FPR"]["note"])
    npos, nneg = int(summ["gt_periodic"]["value"]), int(summ["gt_nonperiodic"]["value"])
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Periodicity detection (E2) after 64 windows, $a_{\\min}{=}0.3$, $T{=}8$, $H{=}3$. "
            "\\emph{Ref.\\ amplitude} is a non-pruning reference model fed the identical occupancy stream. "
            "Periodic TPR $=%d/%d$, FPR $=%d/%d$.}\n" % (tp, npos, fp, nneg))
    f.write("\\label{tab:e2}\n\\small\n\\begin{tabular}{lcccc}\n\\toprule\n")
    f.write("Probe cell & Ground truth & Final class & Ref.\\ amplitude & Outcome \\\\\n\\midrule\n")
    for r in cls:
        gt = r["gt_periodic"] == "1"
        pred = r["pred_periodic"] == "1"
        a = float(r["ref_amplitude"])
        a_s = f"{a:.3f}" if a > 1e-6 else "$\\approx 0$"
        outcome = "correct" if gt == pred else ("\\textbf{miss}" if gt else "\\textbf{false pos.}")
        name = tt(r["cell"]) + (f" ({note[r['cell']]})" if r["cell"] in note else "")
        f.write(f"{name} & {'periodic' if gt else 'non-periodic'} & {r['final_class']} & {a_s} & {outcome} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E3
e3 = rows("e3_sensitivity.csv")


def demlabel(r):
    return "=grad" if r["degenerate"] == "1" else r["demote_prob"]


for lam in ("0.9", "0.97", "1"):
    with open(DATA / f"e3_decay_{lam}.dat", "w") as f:
        f.write("col row flicker f1\n")
        for r in e3:
            if r["survival_decay"] == lam:
                col = {"0.3": 0, "0.5": 1}.get(r["demote_prob"], 2) if r["degenerate"] == "0" else 2
                row = ["0.6", "0.7", "0.8", "0.9"].index(r["graduate_prob"])
                f.write(f"{col} {row} {r['flicker_transitions']} {float(r['final_f1']):.3f}\n")

sel = [("0.9", "0.9", "0.9"), ("0.8", "0.8", "0.9"), ("0.7", "0.7", "0.9"),
       ("0.9", "0.9", "0.97"), ("0.9", "0.9", "1"),
       ("0.9", "0.3", "0.9"), ("0.9", "0.3", "0.97"), ("0.9", "0.3", "1")]
idx = {(r["graduate_prob"], r["demote_prob"], r["survival_decay"]): r for r in e3}
minflick = min(int(r["flicker_transitions"]) for r in e3)
with open(TAB / "e3.tex", "w") as f:
    f.write(HDR % "e3_sensitivity.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Hysteresis and decay ablation (E3), selected rows of the %d-configuration sweep on "
            "identical replayed noise (full sweep in Table~\\ref{tab:e3full}). Band $=p_{\\mathrm{grad}}-p_{\\mathrm{dem}}$; "
            "flicker counts per-window \\texttt{isStatic} toggles over 80 windows. "
            "Bold marks the lowest flicker in the sweep and the worst configuration.}\n" % len(e3))
    f.write("\\label{tab:e3}\n\\small\n\\begin{tabular}{cccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & Band & $\\lambda$ & Flicker $\\downarrow$ & F1 $\\uparrow$ \\\\\n\\midrule\n")
    for i, k in enumerate(sel):
        r = idx[k]
        fl = int(r["flicker_transitions"])
        fls = f"{fl}"
        f1s = f"{float(r['final_f1']):.3f}"
        if i == 0 or fl == minflick:
            fls, f1s = f"\\textbf{{{fls}}}", f"\\textbf{{{f1s}}}"
        lam = f"{float(r['survival_decay']):.2f}"
        f.write(f"{r['graduate_prob']} & {r['demote_prob']}{' (deg.)' if r['degenerate']=='1' else ''} & "
                f"{float(r['hysteresis_band']):.1f} & {lam} & {fls} & {f1s} \\\\\n")
        if i in (2, 4):
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

with open(TAB / "e3_full.tex", "w") as f:  # [H]: placed inline in the appendix
    f.write(HDR % "e3_sensitivity.csv")
    f.write("\\begin{table}[H]\n\\centering\n")
    f.write("\\caption{Full E3 sweep (%d configurations, 50 noisy wall cells, occupancy probability 0.6, "
            "10 movers/window, 80 windows, seed 12345). Deg.\\ marks the zero-band configuration "
            "$p_{\\mathrm{dem}}=p_{\\mathrm{grad}}$.}\n" % len(e3))
    f.write("\\label{tab:e3full}\n\\footnotesize\n\\begin{tabular}{ccccccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & $\\lambda$ & Band & Deg. & F1 & Precision & Recall & Flicker \\\\\n\\midrule\n")
    for i, r in enumerate(e3):
        f.write(f"{r['graduate_prob']} & {r['demote_prob']} & {float(r['survival_decay']):.2f} & "
                f"{float(r['hysteresis_band']):.1f} & {'yes' if r['degenerate']=='1' else 'no'} & "
                f"{float(r['final_f1']):.3f} & {float(r['final_precision']):.3f} & {float(r['final_recall']):.3f} & "
                f"{r['flicker_transitions']} \\\\\n")
        if i % 9 == 8 and i != len(e3) - 1:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E4
e4 = rows("e4_throughput.csv")
with open(DATA / "e4.dat", "w") as f:
    f.write("backend extent us cells upd\n")
    for r in e4:
        f.write(f"{r['backend']} {r['extent']} {float(r['us_per_integrate']):.1f} {r['final_cells']} "
                f"{float(r['cell_updates_per_sec'])/1e6:.3f}\n")


def mem(b):
    b = float(b)
    if b < 1e6:
        return f"{b/1e3:.0f}~KB"
    mb = b / 1e6
    return (f"{mb:.2f}" if mb < 10 else f"{mb:.1f}") + "~MB"


def sci(x):
    x = float(x)
    e = len(str(int(x))) - 1
    return f"${x/10**e:.2f}{{\\times}}10^{{{e}}}$"


by = {(r["backend"], r["extent"]): r for r in e4}
with open(TAB / "e4.tex", "w") as f:
    f.write(HDR % "e4_throughput.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Cost of the shared engine under each backend (E4): 150 random hits per window, 20 windows, "
            "resolution 1.0, periodicity off. Latency and throughput are single-machine wall-clock samples; "
            "live-cell counts, ratios and memory (at %s~B per cell) are geometry-determined and reproducible. "
            "Ratios are voxel3d over grid2d at equal extent; bold marks the cheaper backend.}\n" % e4[0]["bytes_per_cell"])
    f.write("\\label{tab:e4}\n\\small\n\\begin{tabular}{llrrrr}\n\\toprule\n")
    f.write("Backend & Extent & $\\mu$s / \\texttt{integrate} $\\downarrow$ & Cell updates/s & Live cells & Memory \\\\\n\\midrule\n")
    for x in sorted({r["extent"] for r in e4}, key=int):
        g, v = by[("grid2d", x)], by[("voxel3d", x)]
        for r in (g, v):
            us = thou(f"{float(r['us_per_integrate']):.1f}")
            if r is g:
                us = f"\\textbf{{{us}}}"
            f.write(f"{tt(r['backend'])} & ${x}^2$ & {us} & {sci(r['cell_updates_per_sec'])} & "
                    f"{thou(r['final_cells'])} & {mem(r['est_bytes'])} \\\\\n")
        cr = float(v["us_per_integrate"]) / float(g["us_per_integrate"])
        lr = float(v["final_cells"]) / float(g["final_cells"])
        f.write(f"\\multicolumn{{2}}{{l}}{{\\quad\\emph{{ratio}}}} & \\emph{{{cr:.1f}$\\times$}} & & "
                f"\\emph{{{lr:.1f}$\\times$}} & \\\\\n")
        if x != "500":
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print("wrote", sorted(p.name for p in DATA.iterdir()), "and tables e1 e2 e3 e3_full e4")
