#!/usr/bin/env python3
"""Regenerate every data-bearing figure input and results table of the arXiv
package from the committed harness CSVs in paper/experiments/results/.

    python3 paper/arxiv_ref/tools/make_artifacts.py

Writes figures/data/*.dat (read by pgfplots) and tables/{e1,e2,e3,e3_full,e4,fix}.tex;
the fix table also reads results/pre_fix_2026-09-28/ (the uncentred-amplitude code).
No number in those files is typed by hand."""
import csv
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
RES = PKG.parent / "experiments" / "results"
DATA = PKG / "figures" / "data"
TAB = PKG / "tables"
DATA.mkdir(parents=True, exist_ok=True)


def rows(name):
    with open(RES / name, newline="") as f:
        return [r for r in csv.DictReader(f) if not r[next(iter(r))].startswith("#")]


def tt(s):
    return r"\texttt{" + s.replace("_", r"\_") + "}"


def thou(x):
    """1234567.8 -> 1{,}234{,}567.8 (LaTeX thousands separator)."""
    ip, _, fp = f"{x}".partition(".")
    out = ""
    while len(ip) > 3:
        out = "{,}" + ip[-3:] + out
        ip = ip[:-3]
    return ip + out + ("." + fp if fp else "")


HDR = "%% AUTO-GENERATED by tools/make_artifacts.py from paper/experiments/results/%s -- do not edit\n"

# ---------------------------------------------------------------- E1
e1 = rows("e1_static_quality.csv")
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        with open(DATA / f"e1_{b}_{d}.dat", "w") as f:
            f.write("window f1 precision recall\n")
            for r in e1:
                if r["backend"] == b and r["density"] == d:
                    f.write(f"{r['window']} {float(r['f1']):.6f} {float(r['precision']):.6f} {float(r['recall']):.6f}\n")
last = max(int(r["window"]) for r in e1)
movers = {"low": 5, "med": 25, "high": 100}
lines = []
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        rr = [r for r in e1 if r["backend"] == b and r["density"] == d]
        first_full = min(int(r["window"]) for r in rr if float(r["recall"]) == 1.0)
        fin = [r for r in rr if int(r["window"]) == last][0]
        lines.append((b, d, first_full, fin))
best_p = max(float(l[3]["precision"]) for l in lines if l[1] == "high")
with open(TAB / "e1.tex", "w") as f:
    f.write(HDR % "e1_static_quality.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Static-layer quality (E1) against the %s-cell ground-truth wall set. "
            "\\emph{Recall~1 from} is the first window index $t$ at which recall reaches 1.0 "
            "(it never drops afterwards); precision, F1 and the predicted static-set size are at "
            "the final window $t{=}%d$. Single seed (12345), so no dispersion is reported. "
            "Bold marks the better backend under high clutter.}\n" % (lines[0][3]["gt_static"], last))
    f.write("\\label{tab:e1}\n\\small\n\\begin{tabular}{llcccc}\n\\toprule\n")
    f.write("Backend & Clutter (movers/window) & Recall 1 from & Precision & F1 & $|\\hat{\\mathcal{S}}|$ \\\\\n\\midrule\n")
    for i, (b, d, ff, fin) in enumerate(lines):
        p, f1 = float(fin["precision"]), float(fin["f1"])
        ps, fs = f"{p:.4f}", f"{f1:.4f}"
        if d == "high" and p == best_p:
            ps, fs = f"\\textbf{{{ps}}}", f"\\textbf{{{fs}}}"
        f.write(f"{tt(b)} & {d} ({movers[d]}) & $t{{=}}{ff}$ & {ps} & {fs} & {fin['pred_static']} \\\\\n")
        if i == 2:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E2
amp = rows("e2_amplitude_vs_length.csv")
cells = []
for r in amp:
    if r["cell"] not in cells:
        cells.append(r["cell"])
for c in cells:
    with open(DATA / f"e2_{c}.dat", "w") as f:
        f.write("len amp\n")
        for r in amp:
            if r["cell"] == c:
                f.write(f"{r['obs_length']} {abs(float(r['amplitude'])):.6f}\n")
cls = rows("e2_classification.csv")
summ = {r["metric"]: r for r in rows("e2_summary.csv")}
note = {"door_p8_4on4off": "50\\% duty", "door_p8_2on6off": "25\\% duty",
        "door_p4_2on2off": "50\\% duty"}
with open(TAB / "e2.tex", "w") as f:
    f.write(HDR % "e2_classification.csv, e2_summary.csv")
    tp, fp = int(summ["periodic_TPR"]["note"]), int(summ["periodic_FPR"]["note"])
    npos, nneg = int(summ["gt_periodic"]["value"]), int(summ["gt_nonperiodic"]["value"])
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Periodicity detection (E2) after 64 windows, $a_{\\min}{=}0.3$, $T{=}8$, $H{=}3$. "
            "\\emph{Ref.\\ amplitude} is a non-pruning reference model fed the identical occupancy stream. "
            "Periodic TPR $=%d/%d$, FPR $=%d/%d$.}\n" % (tp, npos, fp, nneg))
    f.write("\\label{tab:e2}\n\\small\n\\begin{tabular}{lcccc}\n\\toprule\n")
    f.write("Probe cell & Ground truth & Final class & Ref.\\ amplitude & Outcome \\\\\n\\midrule\n")
    for r in cls:
        gt = r["gt_periodic"] == "1"
        pred = r["pred_periodic"] == "1"
        a = float(r["ref_amplitude"])
        a_s = f"{a:.3f}" if a > 1e-6 else "$\\approx 0$"
        outcome = "correct" if gt == pred else ("\\textbf{miss}" if gt else "\\textbf{false pos.}")
        name = tt(r["cell"]) + (f" ({note[r['cell']]})" if r["cell"] in note else "")
        f.write(f"{name} & {'periodic' if gt else 'non-periodic'} & {r['final_class']} & {a_s} & {outcome} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E3
e3 = rows("e3_sensitivity.csv")


def demlabel(r):
    return "=grad" if r["degenerate"] == "1" else r["demote_prob"]


for lam in ("0.9", "0.97", "1"):
    with open(DATA / f"e3_decay_{lam}.dat", "w") as f:
        f.write("col row flicker f1\n")
        for r in e3:
            if r["survival_decay"] == lam:
                col = {"0.3": 0, "0.5": 1}.get(r["demote_prob"], 2) if r["degenerate"] == "0" else 2
                row = ["0.6", "0.7", "0.8", "0.9"].index(r["graduate_prob"])
                f.write(f"{col} {row} {r['flicker_transitions']} {float(r['final_f1']):.3f}\n")

sel = [("0.9", "0.9", "0.9"), ("0.8", "0.8", "0.9"), ("0.7", "0.7", "0.9"),
       ("0.9", "0.9", "0.97"), ("0.9", "0.9", "1"),
       ("0.9", "0.3", "0.9"), ("0.9", "0.3", "0.97"), ("0.9", "0.3", "1")]
idx = {(r["graduate_prob"], r["demote_prob"], r["survival_decay"]): r for r in e3}
minflick = min(int(r["flicker_transitions"]) for r in e3)
with open(TAB / "e3.tex", "w") as f:
    f.write(HDR % "e3_sensitivity.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Hysteresis and decay ablation (E3), selected rows of the %d-configuration sweep on "
            "identical replayed noise (full sweep in Table~\\ref{tab:e3full}). Band $=p_{\\mathrm{grad}}-p_{\\mathrm{dem}}$; "
            "flicker counts per-window \\texttt{isStatic} toggles over 80 windows. "
            "Bold marks the lowest flicker in the sweep and the worst configuration.}\n" % len(e3))
    f.write("\\label{tab:e3}\n\\small\n\\begin{tabular}{cccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & Band & $\\lambda$ & Flicker $\\downarrow$ & F1 $\\uparrow$ \\\\\n\\midrule\n")
    for i, k in enumerate(sel):
        r = idx[k]
        fl = int(r["flicker_transitions"])
        fls = f"{fl}"
        f1s = f"{float(r['final_f1']):.3f}"
        if i == 0 or fl == minflick:
            fls, f1s = f"\\textbf{{{fls}}}", f"\\textbf{{{f1s}}}"
        lam = f"{float(r['survival_decay']):.2f}"
        f.write(f"{r['graduate_prob']} & {r['demote_prob']}{' (deg.)' if r['degenerate']=='1' else ''} & "
                f"{float(r['hysteresis_band']):.1f} & {lam} & {fls} & {f1s} \\\\\n")
        if i in (2, 4):
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

e3p = rows("e3_sensitivity_periodic.csv")
assert [(r["graduate_prob"], r["demote_prob"], r["survival_decay"]) for r in e3] == \
       [(r["graduate_prob"], r["demote_prob"], r["survival_decay"]) for r in e3p]
f1same = sum(r["final_f1"] == rp["final_f1"] for r, rp in zip(e3, e3p))
with open(TAB / "e3_full.tex", "w") as f:  # [H]: placed inline in the appendix
    f.write(HDR % "e3_sensitivity.csv, e3_sensitivity_periodic.csv")
    f.write("\\begin{table}[H]\n\\centering\n")
    f.write("\\caption{Full E3 sweep (%d configurations, 50 noisy wall cells, occupancy probability 0.6, "
            "10 movers/window, 80 windows, seed 12345). Deg.\\ marks the zero-band configuration "
            "$p_{\\mathrm{dem}}=p_{\\mathrm{grad}}$. F1 to Flicker: periodicity off. "
            "\\emph{Flicker, P on}: the same sweep with periodicity on at the shipped $T{=}24$, $H{=}2$, "
            "$a_{\\min}{=}0.3$ (corrected engine; its F1 equals the periodicity-off F1 in %d of %d rows).}\n"
            % (len(e3), f1same, len(e3)))
    f.write("\\label{tab:e3full}\n\\footnotesize\n\\begin{tabular}{cccccccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & $\\lambda$ & Band & Deg. & F1 & Precision & Recall & Flicker & Flicker, P on \\\\\n\\midrule\n")
    for i, (r, rp) in enumerate(zip(e3, e3p)):
        f.write(f"{r['graduate_prob']} & {r['demote_prob']} & {float(r['survival_decay']):.2f} & "
                f"{float(r['hysteresis_band']):.1f} & {'yes' if r['degenerate']=='1' else 'no'} & "
                f"{float(r['final_f1']):.3f} & {float(r['final_precision']):.3f} & {float(r['final_recall']):.3f} & "
                f"{r['flicker_transitions']} & {rp['flicker_transitions']} \\\\\n")
        if i % 9 == 8 and i != len(e3) - 1:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- centring fix: before / after
PRE = "pre_fix_2026-09-28"


def e1_leak(name):
    """Windows t>=3 at which Static recall < 1, over the six backend/clutter runs."""
    rr = rows(name)
    bad = {}
    for r in rr:
        if int(r["window"]) >= 3 and float(r["recall"]) < 1.0:
            bad.setdefault((r["backend"], r["density"]), []).append(int(r["window"]))
    last = max(int(r["window"]) for r in rr)
    fin = [float(r["recall"]) for r in rr if int(r["window"]) == last]
    return bad, min(fin), max(fin)


def e1_cell(name):
    bad, lo, hi = e1_leak(name)
    if not bad:
        return "0 windows", (f"{lo:g}" if lo == hi else f"{lo:g}--{hi:g}")
    ws = sorted({tuple(v) for v in bad.values()})
    assert len(ws) == 1 and len(bad) == 6, "leak differs across runs"
    w = ws[0]
    return f"{len(w)} ($t{{=}}{w[0]}$--${w[-1]}$)", (f"{lo:g}" if lo == hi else f"{lo:g}--{hi:g}")


def e2_sweep(name):
    sw = rows(name)
    fp = [int(r["fp"]) for r in sw]
    tp = [int(r["tp"]) for r in sw]
    wall = sum("wall_constant" in r["false_positives"].split(";") for r in sw)
    return dict(n0=int(sw[0]["obs_length"]), n1=int(sw[-1]["obs_length"]), N=len(sw),
                neg=int(sw[0]["gt_nonperiodic"]), pos=int(sw[0]["gt_periodic"]),
                mfpr=sum(fp) / (len(fp) * int(sw[0]["gt_nonperiodic"])), fpmin=min(fp), fpmax=max(fp),
                tpset=sorted(set(tp)), wall=wall, clean=sum(v == 0 for v in fp), rows=sw)


def summ64(prefix):
    d = {r["metric"]: r for r in rows(prefix + "e2_summary.csv")}
    return int(d["periodic_TPR"]["note"]), int(d["periodic_FPR"]["note"]), \
        int(d["gt_periodic"]["value"]), int(d["gt_nonperiodic"]["value"])


def e3_tot(name):
    rr = rows(name)
    return sum(int(r["flicker_transitions"]) for r in rr), \
        {(r["graduate_prob"], r["demote_prob"], r["survival_decay"]): r for r in rr}


s_pre, s_post = e2_sweep(PRE + "/e2_rates_vs_length.csv"), e2_sweep("e2_rates_vs_length.csv")
for tag, sw in (("pre", s_pre), ("post", s_post)):
    with open(DATA / f"e2_fpr_{tag}.dat", "w") as f:
        f.write("len fpr fp\n")
        for r in sw["rows"]:
            f.write(f"{r['obs_length']} {float(r['fpr']):.6f} {r['fp']}\n")
e1off, _ = e1_cell("e1_static_quality.csv")
e1pre, e1pre_fin = e1_cell(PRE + "/e1_static_quality_periodic.csv")
e1post, e1post_fin = e1_cell("e1_static_quality_periodic.csv")
_, e1off_fin = e1_cell("e1_static_quality.csv")
t_pre, t_post = summ64(PRE + "/"), summ64("")
f_off, i_off = e3_tot("e3_sensitivity.csv")
f_pre, i_pre = e3_tot(PRE + "/e3_sensitivity_periodic.csv")
f_post, i_post = e3_tot("e3_sensitivity_periodic.csv")
K = ("0.9", "0.3", "0.9")
W = ("0.9", "0.9", "0.9")
with open(TAB / "fix.tex", "w") as f:
    f.write(HDR % ("e1_static_quality{,_periodic}.csv, e2_summary.csv, e2_rates_vs_length.csv, "
                   "e3_sensitivity{,_periodic}.csv and " + PRE + "/"))
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Effect of centring the Fourier coefficients (\\S\\ref{subsec:fremen}), same harness, seeds and "
            "parameters. \\emph{Pre-fix}: the uncentred amplitude of the v0.1.0 code (results kept in "
            "\\nolinkurl{results/%s/}); \\emph{post-fix}: the corrected engine. E1 and E3 with periodicity on use "
            "the shipped $T{=}24$, $H{=}2$, $a_{\\min}{=}0.3$; E2 uses $T{=}8$, $H{=}3$. E1 counts are identical in all six backend--clutter runs.}\n" % PRE.replace("_", "\\_"))
    f.write("\\label{tab:fix}\n\\footnotesize\n\\begin{tabular}{lccc}\n\\toprule\n")
    f.write("Measure & Periodicity off & On, pre-fix & On, post-fix \\\\\n\\midrule\n")
    f.write(f"E1: windows $t\\ge3$ with Static recall $<1$ & {e1off} & {e1pre} & {e1post} \\\\\n")
    f.write(f"E1: Static recall at $t{{=}}39$ & {e1off_fin} & {e1pre_fin} & {e1post_fin} \\\\\n\\midrule\n")
    f.write(f"E2 at $n{{=}}64$: TPR / FPR & -- & {t_pre[0]}/{t_pre[2]} / {t_pre[1]}/{t_pre[3]} & "
            f"{t_post[0]}/{t_post[2]} / {t_post[1]}/{t_post[3]} \\\\\n")
    f.write(f"E2, $n={s_pre['n0']}$--${s_pre['n1']}$: mean FPR & -- & {s_pre['mfpr']:.3f} & {s_post['mfpr']:.3f} \\\\\n")
    f.write(f"E2, $n={s_pre['n0']}$--${s_pre['n1']}$: FP count range (of {s_pre['neg']}) & -- & "
            f"{s_pre['fpmin']}--{s_pre['fpmax']} & {s_post['fpmin']}--{s_post['fpmax']} \\\\\n")
    f.write(f"E2, $n={s_pre['n0']}$--${s_pre['n1']}$: lengths with constant wall Periodic & -- & "
            f"{s_pre['wall']} of {s_pre['N']} & {s_post['wall']} of {s_post['N']} \\\\\n")
    f.write(f"E2, $n={s_pre['n0']}$--${s_pre['n1']}$: lengths with no FP & -- & "
            f"{s_pre['clean']} of {s_pre['N']} & {s_post['clean']} of {s_post['N']} \\\\\n\\midrule\n")
    f.write(f"E3: total flicker, 36 configurations & {f_off} & {f_pre} & {f_post} \\\\\n")
    f.write(f"E3: flicker at $\\pgrad{{=}}0.9$, $\\pdem{{=}}0.3$, $\\lambda{{=}}0.90$ & "
            f"{i_off[K]['flicker_transitions']} & {i_pre[K]['flicker_transitions']} & {i_post[K]['flicker_transitions']} \\\\\n")
    f.write(f"E3: flicker at $\\pgrad{{=}}\\pdem{{=}}0.9$, $\\lambda{{=}}0.90$ & "
            f"{i_off[W]['flicker_transitions']} & {i_pre[W]['flicker_transitions']} & {i_post[W]['flicker_transitions']} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E4
e4 = rows("e4_throughput.csv")
with open(DATA / "e4.dat", "w") as f:
    f.write("backend extent us cells upd\n")
    for r in e4:
        f.write(f"{r['backend']} {r['extent']} {float(r['us_per_integrate']):.1f} {r['final_cells']} "
                f"{float(r['cell_updates_per_sec'])/1e6:.3f}\n")


def mem(b):
    b = float(b)
    if b < 1e6:
        return f"{b/1e3:.0f}~KB"
    mb = b / 1e6
    return (f"{mb:.2f}" if mb < 10 else f"{mb:.1f}") + "~MB"


def sci(x):
    x = float(x)
    e = len(str(int(x))) - 1
    return f"${x/10**e:.2f}{{\\times}}10^{{{e}}}$"


by = {(r["backend"], r["extent"]): r for r in e4}
with open(TAB / "e4.tex", "w") as f:
    f.write(HDR % "e4_throughput.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Cost of the shared engine under each backend (E4): 150 random hits per window, 20 windows, "
            "resolution 1.0, periodicity off. Latency and throughput are single-machine wall-clock samples; "
            "live-cell counts, ratios and memory (at %s~B per cell) are geometry-determined and reproducible. "
            "Ratios are voxel3d over grid2d at equal extent; bold marks the cheaper backend.}\n" % e4[0]["bytes_per_cell"])
    f.write("\\label{tab:e4}\n\\small\n\\begin{tabular}{llrrrr}\n\\toprule\n")
    f.write("Backend & Extent & $\\mu$s / \\texttt{integrate} $\\downarrow$ & Cell updates/s & Live cells & Memory \\\\\n\\midrule\n")
    for x in sorted({r["extent"] for r in e4}, key=int):
        g, v = by[("grid2d", x)], by[("voxel3d", x)]
        for r in (g, v):
            us = thou(f"{float(r['us_per_integrate']):.1f}")
            if r is g:
                us = f"\\textbf{{{us}}}"
            f.write(f"{tt(r['backend'])} & ${x}^2$ & {us} & {sci(r['cell_updates_per_sec'])} & "
                    f"{thou(r['final_cells'])} & {mem(r['est_bytes'])} \\\\\n")
        cr = float(v["us_per_integrate"]) / float(g["us_per_integrate"])
        lr = float(v["final_cells"]) / float(g["final_cells"])
        f.write(f"\\multicolumn{{2}}{{l}}{{\\quad\\emph{{ratio}}}} & \\emph{{{cr:.1f}$\\times$}} & & "
                f"\\emph{{{lr:.1f}$\\times$}} & \\\\\n")
        if x != "500":
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print("wrote", sorted(p.name for p in DATA.iterdir()), "and tables e1 e2 e3 e3_full e4 fix")
