#!/usr/bin/env python3
"""Regenerate every data-bearing figure input and results table of the arXiv
package from the committed harness CSVs in paper/experiments/results/.

    python3 paper/arxiv_ref/tools/make_artifacts.py

Writes figures/data/*.dat (read by pgfplots) and tables/{e0,e1,e2,e3,e3_full,e4,fix}.tex;
the fix table also reads results/pre_fix_2026-09-28/ (the uncentred-amplitude code) and
results/pre_calibration_2026-09-28/ (centred, amplitude-only periodic rule).
No number in those files is typed by hand."""
import csv
import math
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
RES = PKG.parent / "experiments" / "results"
DATA = PKG / "figures" / "data"
TAB = PKG / "tables"
DATA.mkdir(parents=True, exist_ok=True)


def rows(name):
    with open(RES / name, newline="") as f:
        return [r for r in csv.DictReader(f) if not r[next(iter(r))].startswith("#")]


def tt(s):
    return r"\texttt{" + s.replace("_", r"\_") + "}"


def thou(x):
    """1234567.8 -> 1{,}234{,}567.8 (LaTeX thousands separator)."""
    ip, _, fp = f"{x}".partition(".")
    out = ""
    while len(ip) > 3:
        out = "{,}" + ip[-3:] + out
        ip = ip[:-3]
    return ip + out + ("." + fp if fp else "")


HDR = "%% AUTO-GENERATED by tools/make_artifacts.py from paper/experiments/results/%s -- do not edit\n"

# ---------------------------------------------------------------- E1
e1 = rows("e1_static_quality.csv")
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        with open(DATA / f"e1_{b}_{d}.dat", "w") as f:
            f.write("window f1 precision recall\n")
            for r in e1:
                if r["backend"] == b and r["density"] == d:
                    f.write(f"{r['window']} {float(r['f1']):.6f} {float(r['precision']):.6f} {float(r['recall']):.6f}\n")
last = max(int(r["window"]) for r in e1)
movers = {"low": 5, "med": 25, "high": 100}
lines = []
for b in ("grid2d", "voxel3d"):
    for d in ("low", "med", "high"):
        rr = [r for r in e1 if r["backend"] == b and r["density"] == d]
        first_full = min(int(r["window"]) for r in rr if float(r["recall"]) == 1.0)
        fin = [r for r in rr if int(r["window"]) == last][0]
        lines.append((b, d, first_full, fin))
best_p = max(float(l[3]["precision"]) for l in lines if l[1] == "high")
with open(TAB / "e1.tex", "w") as f:
    f.write(HDR % "e1_static_quality.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Static-layer quality (E1) against the %s-cell ground-truth wall set. "
            "\\emph{Recall~1 from} is the first window index $t$ at which recall reaches 1.0 "
            "(it never drops afterwards); precision, F1 and the predicted static-set size are at "
            "the final window $t{=}%d$. Single seed (12345), so no dispersion is reported. "
            "Bold marks the better backend under high clutter.}\n" % (lines[0][3]["gt_static"], last))
    f.write("\\label{tab:e1}\n\\small\n\\begin{tabular}{llcccc}\n\\toprule\n")
    f.write("Backend & Clutter (movers/window) & Recall 1 from & Precision & F1 & $|\\hat{\\mathcal{S}}|$ \\\\\n\\midrule\n")
    for i, (b, d, ff, fin) in enumerate(lines):
        p, f1 = float(fin["precision"]), float(fin["f1"])
        ps, fs = f"{p:.4f}", f"{f1:.4f}"
        if d == "high" and p == best_p:
            ps, fs = f"\\textbf{{{ps}}}", f"\\textbf{{{fs}}}"
        f.write(f"{tt(b)} & {d} ({movers[d]}) & $t{{=}}{ff}$ & {ps} & {fs} & {fin['pred_static']} \\\\\n")
        if i == 2:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E0 (calibration) + chosen level
e0 = rows("e0_calibration_choice.csv")
e0sel = [r for r in e0 if r["selected"] == "1"]
assert len(e0sel) == 1, "calibration must select exactly one level"
DELTA = float(e0sel[0]["alpha"])
beta_worst = [r for r in csv.DictReader(open(RES / "e0_calibration_choice.csv")) if r["alpha"].startswith("#beta")][0]
with open(TAB / "e0.tex", "w") as f:
    f.write(HDR % "e0_calibration_choice.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Calibration of the nominal level $\\delta$ (E0) on seeds disjoint from E1--E4. "
            "\\emph{Null}: worst false-alarm rate over the grid of iid Bernoulli($m$) streams "
            "($T/H\\in\\{8/3,24/2\\}$, $m\\in[0.05,0.95]$, $n\\ge T$, 20{,}000 streams per point); "
            "\\emph{Pipeline}: worst per-read-out rate of 3000 clutter cells in the live \\code{LayeredMap} (E2 "
            "parameters, pruning on, $n=8$--$100$); \\emph{Door}: median read-out length from which a 4-on/4-off "
            "door stays Periodic (40 phases). Rule, fixed before the run: the largest $\\delta$ with both rates "
            "$\\le 0.01$. For comparison, the Gaussian-residual approximation of the periodogram at level 0.01 "
            "reaches a null rate of %.3f.}\n" % float(beta_worst["worst_null_rate"]))
    f.write("\\label{tab:e0}\n\\small\n\\begin{tabular}{ccccc}\n\\toprule\n")
    f.write("$\\delta$ & Null rate & Pipeline rate & Door, median first $n$ & Selected \\\\\n\\midrule\n")
    for r in e0:
        sel_ = r["selected"] == "1"
        cells = [f"{float(r['alpha']):g}", f"{float(r['worst_null_rate']):.4f}",
                 f"{float(r['worst_pipeline_rate']):.3f}", f"{int(float(r['door_p8_median_first_n']))}",
                 "yes" if sel_ else ("no (rate $>0.01$)" if r["meets_target"] == "0" else "no")]
        if sel_:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        f.write(" & ".join(cells) + " \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E2
amp = rows("e2_amplitude_vs_length.csv")
cells = []
for r in amp:
    if r["cell"] not in cells:
        cells.append(r["cell"])
for c in cells:
    with open(DATA / f"e2_{c}.dat", "w") as f:
        f.write("len amp\n")
        for r in amp:
            if r["cell"] == c:
                f.write(f"{r['obs_length']} {abs(float(r['amplitude'])):.6f}\n")
# calibrated amplitude threshold at uniform phase coverage, a*(n) = sqrt(2 r* / n) with
# B(r*) = x e^{1-x} = DELTA / H at x = 2 r* (E2: H = 3); B is decreasing for x > 1.
H_E2 = 3
lo_, hi_ = 1.0, 100.0
for _ in range(200):
    mid_ = 0.5 * (lo_ + hi_)
    if mid_ * math.exp(1.0 - mid_) > DELTA / H_E2:
        lo_ = mid_
    else:
        hi_ = mid_
R_STAR = 0.5 * hi_
with open(DATA / "e2_threshold.dat", "w") as f:
    f.write("len astar\n")
    for n in range(8, 71):
        f.write(f"{n} {math.sqrt(2.0 * R_STAR / n):.6f}\n")
cls = rows("e2_classification.csv")
summ = {r["metric"]: r for r in rows("e2_summary.csv")}
note = {"door_p8_4on4off": "50\\% duty", "door_p8_2on6off": "25\\% duty",
        "door_p4_2on2off": "50\\% duty"}
with open(TAB / "e2.tex", "w") as f:
    f.write(HDR % "e2_classification.csv, e2_summary.csv")
    tp, fp = int(summ["periodic_TPR"]["note"]), int(summ["periodic_FPR"]["note"])
    npos, nneg = int(summ["gt_periodic"]["value"]), int(summ["gt_nonperiodic"]["value"])
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Periodicity detection (E2) after 64 windows with the calibrated test, $a_{\\min}{=}0.3$, "
            "$\\delta{=}%g$, $T{=}8$, $H{=}3$. "
            "\\emph{Ref.\\ amplitude} and \\emph{Ref.\\ $H\\,B$} (the Bonferroni-adjusted Chernoff bound of "
            "Proposition~\\ref{prop:chernoff}; Periodic needs $\\le\\delta$) come from a non-pruning reference model fed "
            "the identical occupancy stream. Periodic TPR $=%d/%d$, FPR $=%d/%d$. \\emph{Outcome} scores the Periodic class; "
            "a non-periodic cell ending Static is not a Periodic false positive but is a wrong map label (\\emph{false Static}).}\n" % (DELTA, tp, npos, fp, nneg))
    f.write("\\label{tab:e2}\n\\small\n\\begin{tabular}{lccccc}\n\\toprule\n")
    f.write("Probe cell & Ground truth & Final class & Ref.\\ amplitude & Ref.\\ $H\\,B$ & Outcome \\\\\n\\midrule\n")
    for r in cls:
        gt = r["gt_periodic"] == "1"
        pred = r["pred_periodic"] == "1"
        a = float(r["ref_amplitude"])
        a_s = f"{a:.3f}" if a > 1e-6 else "$\\approx 0$"
        fa = float(r["ref_false_alarm"])
        fa_s = "1" if fa >= 1.0 else (f"{fa:.3f}" if fa >= 1e-3 else "$<10^{-3}$")
        outcome = "correct" if gt == pred else ("\\textbf{miss}" if gt else "\\textbf{false pos.}")
        if not gt and not pred and r["final_class"] == "Static" and r["cell"].startswith("aperiodic"):
            outcome = "\\textbf{false Static}"  # correct for the Periodic class, wrong as a map label
        name = tt(r["cell"]) + (f" ({note[r['cell']]})" if r["cell"] in note else "")
        f.write(f"{name} & {'periodic' if gt else 'non-periodic'} & {r['final_class']} & {a_s} & {fa_s} & {outcome} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E3
e3 = rows("e3_sensitivity.csv")


def demlabel(r):
    return "=grad" if r["degenerate"] == "1" else r["demote_prob"]


for lam in ("0.9", "0.97", "1"):
    with open(DATA / f"e3_decay_{lam}.dat", "w") as f:
        f.write("col row flicker f1\n")
        for r in e3:
            if r["survival_decay"] == lam:
                col = {"0.3": 0, "0.5": 1}.get(r["demote_prob"], 2) if r["degenerate"] == "0" else 2
                row = ["0.6", "0.7", "0.8", "0.9"].index(r["graduate_prob"])
                f.write(f"{col} {row} {r['flicker_transitions']} {float(r['final_f1']):.3f}\n")

sel = [("0.9", "0.9", "0.9"), ("0.8", "0.8", "0.9"), ("0.7", "0.7", "0.9"),
       ("0.9", "0.9", "0.97"), ("0.9", "0.9", "1"),
       ("0.9", "0.3", "0.9"), ("0.9", "0.3", "0.97"), ("0.9", "0.3", "1")]
idx = {(r["graduate_prob"], r["demote_prob"], r["survival_decay"]): r for r in e3}
minflick = min(int(r["flicker_transitions"]) for r in e3)
with open(TAB / "e3.tex", "w") as f:
    f.write(HDR % "e3_sensitivity.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Hysteresis and decay ablation (E3), selected rows of the %d-configuration sweep on "
            "identical replayed noise (full sweep in Table~\\ref{tab:e3full}). Band $=p_{\\mathrm{grad}}-p_{\\mathrm{dem}}$; "
            "flicker counts per-window \\texttt{isStatic} toggles over 80 windows. "
            "Bold marks the lowest flicker in the sweep and the worst configuration.}\n" % len(e3))
    f.write("\\label{tab:e3}\n\\small\n\\begin{tabular}{cccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & Band & $\\lambda$ & Flicker $\\downarrow$ & F1 $\\uparrow$ \\\\\n\\midrule\n")
    for i, k in enumerate(sel):
        r = idx[k]
        fl = int(r["flicker_transitions"])
        fls = f"{fl}"
        f1s = f"{float(r['final_f1']):.3f}"
        if i == 0 or fl == minflick:
            fls, f1s = f"\\textbf{{{fls}}}", f"\\textbf{{{f1s}}}"
        lam = f"{float(r['survival_decay']):.2f}"
        f.write(f"{r['graduate_prob']} & {r['demote_prob']}{' (deg.)' if r['degenerate']=='1' else ''} & "
                f"{float(r['hysteresis_band']):.1f} & {lam} & {fls} & {f1s} \\\\\n")
        if i in (2, 4):
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

e3p = rows("e3_sensitivity_periodic.csv")
assert [(r["graduate_prob"], r["demote_prob"], r["survival_decay"]) for r in e3] == \
       [(r["graduate_prob"], r["demote_prob"], r["survival_decay"]) for r in e3p]
f1same = sum(r["final_f1"] == rp["final_f1"] for r, rp in zip(e3, e3p))
with open(TAB / "e3_full.tex", "w") as f:  # [H]: placed inline in the appendix
    f.write(HDR % "e3_sensitivity.csv, e3_sensitivity_periodic.csv")
    f.write("\\begin{table}[H]\n\\centering\n")
    f.write("\\caption{Full E3 sweep (%d configurations, 50 noisy wall cells, occupancy probability 0.6, "
            "10 movers/window, 80 windows, seed 12345). Deg.\\ marks the zero-band configuration "
            "$p_{\\mathrm{dem}}=p_{\\mathrm{grad}}$. F1 to Flicker: periodicity off. "
            "\\emph{Flicker, P on}: the same sweep with periodicity on at the shipped $T{=}24$, $H{=}2$, "
            "$a_{\\min}{=}0.3$, $\\delta{=}%g$ (current engine; its F1 equals the periodicity-off F1 in %d of %d rows).}\n"
            % (len(e3), DELTA, f1same, len(e3)))
    f.write("\\label{tab:e3full}\n\\footnotesize\n\\begin{tabular}{cccccccccc}\n\\toprule\n")
    f.write("$p_{\\mathrm{grad}}$ & $p_{\\mathrm{dem}}$ & $\\lambda$ & Band & Deg. & F1 & Precision & Recall & Flicker & Flicker, P on \\\\\n\\midrule\n")
    for i, (r, rp) in enumerate(zip(e3, e3p)):
        f.write(f"{r['graduate_prob']} & {r['demote_prob']} & {float(r['survival_decay']):.2f} & "
                f"{float(r['hysteresis_band']):.1f} & {'yes' if r['degenerate']=='1' else 'no'} & "
                f"{float(r['final_f1']):.3f} & {float(r['final_precision']):.3f} & {float(r['final_recall']):.3f} & "
                f"{r['flicker_transitions']} & {rp['flicker_transitions']} \\\\\n")
        if i % 9 == 8 and i != len(e3) - 1:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- fixes: before / after
PRE = "pre_fix_2026-09-28"          # v0.1.0: uncentred amplitude, amplitude-only rule
MID = "pre_calibration_2026-09-28"  # centred amplitude, amplitude-only rule


def e1_leak(name):
    """Windows t>=3 at which Static recall < 1, over the six backend/clutter runs."""
    rr = rows(name)
    bad = {}
    for r in rr:
        if int(r["window"]) >= 3 and float(r["recall"]) < 1.0:
            bad.setdefault((r["backend"], r["density"]), []).append(int(r["window"]))
    last = max(int(r["window"]) for r in rr)
    fin = [float(r["recall"]) for r in rr if int(r["window"]) == last]
    return bad, min(fin), max(fin)


def e1_cell(name):
    bad, lo, hi = e1_leak(name)
    if not bad:
        return "0 windows", (f"{lo:g}" if lo == hi else f"{lo:g}--{hi:g}")
    ws = sorted({tuple(v) for v in bad.values()})
    assert len(ws) == 1 and len(bad) == 6, "leak differs across runs"
    w = ws[0]
    return f"{len(w)} ($t{{=}}{w[0]}$--${w[-1]}$)", (f"{lo:g}" if lo == hi else f"{lo:g}--{hi:g}")


def e2_sweep(name):
    sw = rows(name)
    fp = [int(r["fp"]) for r in sw]
    tp = [int(r["tp"]) for r in sw]
    pos = int(sw[0]["gt_periodic"])
    wall = sum("wall_constant" in r["false_positives"].split(";") for r in sw)
    # first read-out length from which TP stays at its maximum through the end of the sweep
    tmax = max(tp)
    stable = next(int(sw[i]["obs_length"]) for i in range(len(sw)) if all(t == tmax for t in tp[i:]))
    ref = None
    if "ref_fp" in sw[0]:
        rfp = [int(r["ref_fp"]) for r in sw]
        rtp = [int(r["ref_tp"]) for r in sw]
        ref = dict(mfpr=sum(rfp) / (len(rfp) * int(sw[0]["gt_nonperiodic"])), fpmax=max(rfp),
                   fplens=sum(v > 0 for v in rfp), mtpr=sum(rtp) / (len(rtp) * pos),
                   full=next(int(sw[i]["obs_length"]) for i in range(len(sw)) if all(t == pos for t in rtp[i:])),
                   cells=sorted({c for r in sw for c in r["ref_false_positives"].split(";") if c != "-"}))
    return dict(n0=int(sw[0]["obs_length"]), n1=int(sw[-1]["obs_length"]), N=len(sw), ref=ref,
                neg=int(sw[0]["gt_nonperiodic"]), pos=pos,
                mfpr=sum(fp) / (len(fp) * int(sw[0]["gt_nonperiodic"])), fpmin=min(fp), fpmax=max(fp),
                mtpr=sum(tp) / (len(tp) * pos), tpmin=min(tp), tpmax=tmax, stable=stable,
                wall=wall, clean=sum(v == 0 for v in fp), rows=sw)


def summ64(prefix):
    d = {r["metric"]: r for r in rows(prefix + "e2_summary.csv")}
    return int(d["periodic_TPR"]["note"]), int(d["periodic_FPR"]["note"]), \
        int(d["gt_periodic"]["value"]), int(d["gt_nonperiodic"]["value"])


def e3_tot(name):
    rr = rows(name)
    return sum(int(r["flicker_transitions"]) for r in rr), \
        {(r["graduate_prob"], r["demote_prob"], r["survival_decay"]): r for r in rr}


S = {"pre": e2_sweep(PRE + "/e2_rates_vs_length.csv"), "mid": e2_sweep(MID + "/e2_rates_vs_length.csv"),
     "post": e2_sweep("e2_rates_vs_length.csv")}
for tag, sw in S.items():
    with open(DATA / f"e2_fpr_{tag}.dat", "w") as f:
        f.write("len fpr fp tpr tp" + (" reffpr reftpr" if sw["ref"] else "") + "\n")
        for r in sw["rows"]:
            extra = ""
            if sw["ref"]:
                extra = f" {int(r['ref_fp']) / int(r['gt_nonperiodic']):.6f} {int(r['ref_tp']) / int(r['gt_periodic']):.6f}"
            f.write(f"{r['obs_length']} {float(r['fpr']):.6f} {r['fp']} {float(r['tpr']):.6f} {r['tp']}{extra}\n")
e1off, e1off_fin = e1_cell("e1_static_quality.csv")
e1pre, e1pre_fin = e1_cell(PRE + "/e1_static_quality_periodic.csv")
e1mid, e1mid_fin = e1_cell(MID + "/e1_static_quality_periodic.csv")
e1post, e1post_fin = e1_cell("e1_static_quality_periodic.csv")
T64 = {"pre": summ64(PRE + "/"), "mid": summ64(MID + "/"), "post": summ64("")}
f_off, i_off = e3_tot("e3_sensitivity.csv")
F3 = {"pre": e3_tot(PRE + "/e3_sensitivity_periodic.csv"), "mid": e3_tot(MID + "/e3_sensitivity_periodic.csv"),
      "post": e3_tot("e3_sensitivity_periodic.csv")}
K = ("0.9", "0.3", "0.9")
W = ("0.9", "0.9", "0.9")
V = ("pre", "mid", "post")
n0, n1 = S["pre"]["n0"], S["pre"]["n1"]
with open(TAB / "fix.tex", "w") as f:
    f.write(HDR % ("e1_static_quality{,_periodic}.csv, e2_summary.csv, e2_rates_vs_length.csv, "
                   "e3_sensitivity{,_periodic}.csv, " + PRE + "/ and " + MID + "/"))
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Effect of the two corrections to the periodicity test, same harness, seeds and parameters. "
            "\\emph{v0.1.0}: uncentred amplitude and the amplitude-only rule $a\\ge\\amin$ (results in "
            "\\nolinkurl{results/%s/}); \\emph{Centred}: centred amplitude, amplitude-only rule "
            "(\\nolinkurl{results/%s/}); \\emph{Calibrated}: centred amplitude and the significance test of "
            "Proposition~\\ref{prop:chernoff} at $\\delta{=}%g$ (current engine). E1 and E3 with periodicity on use the "
            "shipped $T{=}24$, $H{=}2$, $\\amin{=}0.3$; E2 uses $T{=}8$, $H{=}3$. E1 counts are identical in all six "
            "backend--clutter runs.}\n" % (PRE.replace("_", "\\_"), MID.replace("_", "\\_"), DELTA))
    f.write("\\label{tab:fix}\n\\footnotesize\n\\setlength{\\tabcolsep}{4pt}\n\\begin{tabular}{lcccc}\n\\toprule\n")
    f.write("& Periodicity & \\multicolumn{3}{c}{Periodicity on} \\\\\n\\cmidrule(lr){3-5}\n")
    f.write("Measure & off & v0.1.0 & Centred & Calibrated \\\\\n\\midrule\n")
    f.write(f"E1: windows $t\\ge3$ with Static recall $<1$ & {e1off} & {e1pre} & {e1mid} & {e1post} \\\\\n")
    f.write(f"E1: Static recall at $t{{=}}39$ & {e1off_fin} & {e1pre_fin} & {e1mid_fin} & {e1post_fin} \\\\\n\\midrule\n")
    f.write("E2 at $n{=}64$: TPR / FPR & -- & " + " & ".join(
        f"{T64[v][0]}/{T64[v][2]} / {T64[v][1]}/{T64[v][3]}" for v in V) + " \\\\\n")
    f.write(f"E2, $n={n0}$--${n1}$: mean FPR & -- & " + " & ".join(f"{S[v]['mfpr']:.3f}" for v in V) + " \\\\\n")
    f.write(f"E2, $n={n0}$--${n1}$: FP count range (of {S['pre']['neg']}) & -- & " +
            " & ".join(f"{S[v]['fpmin']}--{S[v]['fpmax']}" for v in V) + " \\\\\n")
    f.write(f"E2, $n={n0}$--${n1}$: lengths with no FP & -- & " +
            " & ".join(f"{S[v]['clean']} of {S[v]['N']}" for v in V) + " \\\\\n")
    f.write(f"E2, $n={n0}$--${n1}$: lengths with constant wall Periodic & -- & " +
            " & ".join(f"{S[v]['wall']} of {S[v]['N']}" for v in V) + " \\\\\n")
    f.write(f"E2, $n={n0}$--${n1}$: mean TPR & -- & " + " & ".join(f"{S[v]['mtpr']:.3f}" for v in V) + " \\\\\n")
    f.write(f"E2: TPR {S['pre']['tpmax']}/{S['pre']['pos']} at every $n\\ge$ & -- & " +
            " & ".join(f"{S[v]['stable']}" for v in V) + " \\\\\n\\midrule\n")
    f.write("E3: total flicker, 36 configurations & " + f"{f_off} & " +
            " & ".join(f"{F3[v][0]}" for v in V) + " \\\\\n")
    f.write("E3: flicker at $\\pgrad{=}0.9$, $\\pdem{=}0.3$, $\\lambda{=}0.90$ & " +
            f"{i_off[K]['flicker_transitions']} & " + " & ".join(F3[v][1][K]["flicker_transitions"] for v in V) + " \\\\\n")
    f.write("E3: flicker at $\\pgrad{=}\\pdem{=}0.9$, $\\lambda{=}0.90$ & " +
            f"{i_off[W]['flicker_transitions']} & " + " & ".join(F3[v][1][W]["flicker_transitions"] for v in V) + " \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

# ---------------------------------------------------------------- E4
e4 = rows("e4_throughput.csv")
with open(DATA / "e4.dat", "w") as f:
    f.write("backend extent us cells upd\n")
    for r in e4:
        f.write(f"{r['backend']} {r['extent']} {float(r['us_per_integrate']):.1f} {r['final_cells']} "
                f"{float(r['cell_updates_per_sec'])/1e6:.3f}\n")


def mem(b):
    b = float(b)
    if b < 1e6:
        return f"{b/1e3:.0f}~KB"
    mb = b / 1e6
    return (f"{mb:.2f}" if mb < 10 else f"{mb:.1f}") + "~MB"


def sci(x):
    x = float(x)
    e = len(str(int(x))) - 1
    return f"${x/10**e:.2f}{{\\times}}10^{{{e}}}$"


by = {(r["backend"], r["extent"]): r for r in e4}
with open(TAB / "e4.tex", "w") as f:
    f.write(HDR % "e4_throughput.csv")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Cost of the shared engine under each backend (E4): 150 random hits per window, 20 windows, "
            "resolution 1.0, periodicity off. Latency and throughput are single-machine wall-clock samples; "
            "live-cell counts, ratios and memory (at %s~B per cell) are geometry-determined and reproducible. "
            "Ratios are voxel3d over grid2d at equal extent; bold marks the cheaper backend.}\n" % e4[0]["bytes_per_cell"])
    f.write("\\label{tab:e4}\n\\small\n\\begin{tabular}{llrrrr}\n\\toprule\n")
    f.write("Backend & Extent & $\\mu$s / \\texttt{integrate} $\\downarrow$ & Cell updates/s & Live cells & Memory \\\\\n\\midrule\n")
    for x in sorted({r["extent"] for r in e4}, key=int):
        g, v = by[("grid2d", x)], by[("voxel3d", x)]
        for r in (g, v):
            us = thou(f"{float(r['us_per_integrate']):.1f}")
            if r is g:
                us = f"\\textbf{{{us}}}"
            f.write(f"{tt(r['backend'])} & ${x}^2$ & {us} & {sci(r['cell_updates_per_sec'])} & "
                    f"{thou(r['final_cells'])} & {mem(r['est_bytes'])} \\\\\n")
        cr = float(v["us_per_integrate"]) / float(g["us_per_integrate"])
        lr = float(v["final_cells"]) / float(g["final_cells"])
        f.write(f"\\multicolumn{{2}}{{l}}{{\\quad\\emph{{ratio}}}} & \\emph{{{cr:.1f}$\\times$}} & & "
                f"\\emph{{{lr:.1f}$\\times$}} & \\\\\n")
        if x != "500":
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print("wrote", sorted(p.name for p in DATA.iterdir()), "and tables e0 e1 e2 e3 e3_full e4 fix")
